package com.tekcapsule.subscription.domain.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.tekcapsule.core.domain.AggregateRoot;
import com.tekcapsule.core.domain.BaseDomainEntity;
import lombok.*;
import software.amazon.ion.Decimal;

import java.util.List;
@Data
@JsonIgnoreProperties(ignoreUnknown = true)
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = "Subscription")
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class Transaction extends BaseDomainEntity implements AggregateRoot {

    @DynamoDBHashKey(attributeName="transactionId")
    @DynamoDBAutoGeneratedKey
    private String transactionId;
    @DynamoDBAttribute(attributeName="emailId")
    private String transactedOn;
    @DynamoDBAttribute(attributeName="emailId")
    private String externalReferenceId;
    @DynamoDBAttribute(attributeName="emailId")
    private String invoiceId;
    @DynamoDBAttribute(attributeName="emailId")
    @DynamoDBTypeConvertedEnum
    private PaymentMethod paymentMethod;
    @DynamoDBAttribute(attributeName="emailId")
    @DynamoDBTypeConvertedEnum
    private TransactionType transactionType;
    @DynamoDBAttribute(attributeName="emailId")
    @DynamoDBTypeConvertedEnum
    private Currency currency;
    @DynamoDBAttribute(attributeName="emailId")
    private Decimal amount;
    @DynamoDBAttribute(attributeName="emailId")
    private BillingPeriod billingPeriod;
    @DynamoDBAttribute(attributeName="emailId")
    private List<Comment> comments;
    @DynamoDBAttribute(attributeName="emailId")
    @DynamoDBTypeConvertedEnum
    private Status status;
}
